# frozen_string_literal: true

# MUST KEEP THESE HASHES IN SYNC !!

TEAMS = {
  0 => 'Arizona Cardinals',
  1 => 'Atlanta Falcons',
  2 => 'Baltimore Ravens',
  3 => 'Buffalo Bills',
  4 => 'Carolina Panthers',
  5 => 'Chicago Bears',
  6 => 'Cincinnati Bengals',
  7 => 'Cleveland Browns',
  8 => 'Dallas Cowboys',
  9 => 'Denver Broncos',
  10 => 'Detroit Lions',
  11 => 'Green Bay Packers',
  12 => 'Houston Texans',
  13 => 'Indianapolis Colts',
  14 => 'Jacksonville Jaguars',
  15 => 'Kansas City Chiefs',
  16 => 'Los Angeles Chargers',
  17 => 'Los Angeles Rams',
  18 => 'Miami Dolphins',
  19 => 'Minnesota Vikings',
  20 => 'New England Patriots',
  21 => 'New Orleans Saints',
  22 => 'New York Giants',
  23 => 'New York Jets',
  24 => 'Oakland Raiders',
  25 => 'Philadelphia Eagles',
  26 => 'Pittsburgh Steelers',
  27 => 'Seattle Seahawks',
  28 => 'San Francisco 49ers',
  29 => 'Tampa Bay Buccaneers',
  30 => 'Tennessee Titans',
  31 => 'Washington Redskins'
}.freeze

TEAM_ABBREVIATIONS = {
  0 => 'ari',
  1 => 'atl',
  2 => 'bal',
  3 => 'buf',
  4 => 'car',
  5 => 'chi',
  6 => 'cin',
  7 => 'cle',
  8 => 'dal',
  9 => 'den',
  10 => 'det',
  11 => 'gb',
  12 => 'hou',
  13 => 'ind',
  14 => 'jax',
  15 => 'kc',
  16 => 'lac',
  17 => 'lar',
  18 => 'mia',
  19 => 'min',
  20 => 'ne',
  21 => 'no',
  22 => 'nyg',
  23 => 'nyj',
  24 => 'oak',
  25 => 'phi',
  26 => 'pit',
  27 => 'sea',
  28 => 'sf',
  29 => 'tb',
  30 => 'ten',
  31 => 'was'
}.freeze
